###### Release 1.14.0 and 2.0.0 #######

env: prod
env_name: "{{ env }}"
proto: https
domain_name: portal.igotkarmayogi.gov.in
portal_domain_name: portal.igotkarmayogi.gov.in
static_domain_name: igotkarmayogi.gov.in
ssh_public_key_deployer: /var/lib/jenkins/secrets/deployer_ssh_key.pub
bootstrap_user: ansible
bootstrap_key_path: /var/lib/jenkins/secrets/id_rsa


secor_azure_container_name: ""
secor_alerts_slack_channel: ""

####### Azure account name
sunbird_private_storage_account_name:  # Azure account name for analytics api contents
sunbird_artifact_storage_account_name:  # Azure stroage account name used for artifact upload
sunbird_public_storage_account_name: 


default_org_hash_id: "" # channel id of the organization

# Data products monitoring web hooks
data_exhaust_webhook_url: ""   ## Slack webhook
data_exhaust_Channel: ""      ## salck channel for data products alerts
data_exhaust_name:   
stream_base_url: ""

# Media content
media_service_azure_tenant: "" # value have to be defined
media_service_azure_tenant: ""
media_service_azure_subscription_id: ""
media_service_azure_account_name: ""
media_service_azure_resource_group_name: ""
media_service_azure_token_client_key: ""
media_service_azure_token_client_secret: ""

azure_account : igotprod

#Kafka version
kafka_version: 2.4.1

# kafka topic required by core #
# Please do not change this #
kafka_partition_override_size: 5242880
dp_downstream_kafka_max_message_bytes: 1572864

ingestion_kafka_topics:
  - name: telemetry.ingestion
    num_of_partitions: 16
    replication_factor: 2
  - name: events.deviceprofile
    num_of_partitions: 4
    replication_factor: 1

ingestion_kafka_overriden_topics:
  - name: telemetry.ingestion
    retention_time: 259200000
    replication_factor: 2
    max_message_bytes: 5242880
  - name: events.deviceprofile
    retention_time: 172800000
    replication_factor: 1
    

processing_kafka_overriden_topics:
  - name: dashboards.course
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.resource
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.role.count
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.org.role.count
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.course.details
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.user.course.progress
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.user.course.program.progress
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.competency.frac
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.competency.course
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.competency.expected
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.competency.declared
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.competency.gap
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.user.org
    retention_time: 172800000
    replication_factor: 2
  - name: dashboards.course.rating.summary
    retention_time: 172800000
    replication_factor: 2
  - name: analytics.job_queue
    retention_time: 172800000
    replication_factor: 2
  - name: analytics_metrics
    retention_time: 172800000
    replication_factor: 2
  - name: druid.events.error
    retention_time: 172800000
    replication_factor: 2
  - name: druid.events.log
    retention_time: 172800000
    replication_factor: 2
  - name: druid.events.summary
    retention_time: 172800000
    replication_factor: 2
  - name: druid.events.telemetry
    retention_time: 172800000
    replication_factor: 2
  - name: events.error
    retention_time: 172800000
    replication_factor: 2
  - name: events.log
    retention_time: 172800000
    replication_factor: 2
  - name: events.summary
    retention_time: 172800000
    replication_factor: 2
  - name: events.telemetry
    retention_time: 172800000
    replication_factor: 2
  - name: events.deviceprofile
    retention_time: 172800000
    replication_factor: 1
  - name: prom.monitoring.metrics
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.assess
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.assess.failed
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.assess.raw
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.audit
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.denorm
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.derived
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.derived.unique
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.duplicate
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.error
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.extractor.duplicate
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.extractor.failed
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.failed
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.ingest
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.metrics
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.raw
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.unique
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.unique.latest
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.unique.primary
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.unique.secondary
    retention_time: 172800000
    replication_factor: 2
  - name: ml.observation.raw
    retention_time: 172800000
    replication_factor: 2
  - name: ml.observation.druid
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.cb.audit
    retention_time: 172800000
    replication_factor: 2
  - name: druid.cb.audit
    retention_time: 172800000
    replication_factor: 2
  - name: druid.cb.work.order.row
    retention_time: 172800000
    replication_factor: 2
  - name: druid.cb.work.order.officer
    retention_time: 172800000
    replication_factor: 2
  - name: rating.event
    retention_time: 172800000
    replication_factor: 2
  - name: rating.failedRating
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.denorm.valid
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.log
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.sink
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.valid
    retention_time: 172800000
    replication_factor: 2
  - name: telemetry.with_location
    retention_time: 172800000
    replication_factor: 2
  - name: pipeline_metrics
    retention_time: 259200000
    replication_factor: 2

processing_kafka_topics:
  - name: dashboards.course
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.resource
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.role.count
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.org.role.count
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.course.details
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.user.course.progress
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.user.course.program.progress
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.competency.frac
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.competency.course
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.competency.expected
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.competency.declared
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.competency.gap
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.user.org
    num_of_partitions: 4
    replication_factor: 2
  - name: dashboards.course.rating.summary
    num_of_partitions: 4
    replication_factor: 2
  - name: analytics.job_queue
    num_of_partitions: 4
    replication_factor: 2
  - name: analytics_metrics
    num_of_partitions: 4
    replication_factor: 2
  - name: druid.events.error
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.events.log
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.events.summary
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.events.telemetry
    num_of_partitions: 16
    replication_factor: 2
  - name: events.error
    num_of_partitions: 16
    replication_factor: 2
  - name: events.log
    num_of_partitions: 16
    replication_factor: 2
  - name: events.summary
    num_of_partitions: 16
    replication_factor: 2
  - name: events.telemetry
    num_of_partitions: 16
    replication_factor: 2
  - name: events.deviceprofile
    num_of_partitions: 4
    replication_factor: 1
  - name: prom.monitoring.metrics
    num_of_partitions: 4
    replication_factor: 2
  - name: telemetry.assess
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.assess.failed
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.assess.raw
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.audit
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.denorm
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.derived
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.derived.unique
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.duplicate
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.error
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.extractor.duplicate
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.extractor.failed
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.failed
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.ingest
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.metrics
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.raw
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.unique
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.unique.latest
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.unique.primary
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.unique.secondary
    num_of_partitions: 16
    replication_factor: 2
  - name: ml.observation.raw
    num_of_partitions: 4
    replication_factor: 2
  - name: ml.observation.druid
    num_of_partitions: 4
    replication_factor: 2
  - name: telemetry.cb.audit
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.cb.audit
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.cb.work.order.row
    num_of_partitions: 16
    replication_factor: 2
  - name: druid.cb.work.order.officer
    num_of_partitions: 16
    replication_factor: 2
  - name: rating.event
    num_of_partitions: 4
    replication_factor: 2
  - name: rating.failedRating
    num_of_partitions: 4
    replication_factor: 2
  - name: telemetry.denorm.valid
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.log
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.sink
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.valid
    num_of_partitions: 16
    replication_factor: 2
  - name: telemetry.with_location
    num_of_partitions: 16
    replication_factor: 2
  - name: pipeline_metrics
    num_of_partitions: 4
    replication_factor: 2

# Geo location related var
maxmind_db_license_key:

postgres:
  db_url: "{{ groups['postgres'][0] }}"
  db_username: analytics
  db_name: analytics
  db_password: "{{dp_vault_pgdb_password}}"
  db_table_name: "{{env}}_consumer_channel_mapping"
  db_port: 5432
  db_admin_user: postgres
  db_admin_password: "{{dp_vault_pgdb_admin_password}}"
  
sunbird_private_azure_report_container_name: 'reports'
sunbird_public_azure_report_container_name: 'public-reports'
sunbird_druid_storage_account_name: 

dialservice_ip:    ### dial vm ip
dialcode_host: "http://{{dialservice_ip}}:9001"
dialcode_endpoint: "dialcode/v3/read/"

swarm_manager_lb_ip:       # nginx internal service IP, this service expose 80 port from the backend pods 

cephs3_storage_container: igotprod
cephs3_storage_endpoint: http://static.karmayogiprod.nic.in
cephs3_dp_storage_container: igotlogs
metadata2_redis_host: 192.168.3.126
redis_host: 192.168.3.82

content_port: 6379
device_port: 6379
user_port: 6379
dialcode_port: 6379




# docker hub details
dockerhub: chub.cloud.gov.in/nk8s-mission-karmyogi
docker_registry:    ## user
imagepullsecrets: "{{env}}-registry-secret"

kubeconfig_path: /var/lib/jenkins/secrets/k8s.yaml
private_ingressgateway_ip: 10.194.181.122



###########

kafka_brokers: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
zookeepers: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"

ingestion_kafka_brokers: "{{groups['ingestion-cluster-kafka']|join(':9092,')}}:9092"
ingestion_zookeepers: "{{groups['ingestion-cluster-zookeepers']|join(':2181,')}}:2181"

###########New vars dated 06-07-2022
sunbird_private_s3_storage_key: "{{ cephs3_storage_key }}"
sunbird_private_s3_storage_secret: "{{ cephs3_storage_secret }}"

s3_storage_endpoint: "{{ cephs3_storage_endpoint }}"
s3_request_signature_version: AWS4-HMAC-SHA256
s3_path_style_access: true
s3_https_only: false
s3_default_bucket_location: "us-east-1"
s3_storage_container: "{{ cephs3_storage_container }}"
s3_dp_storage_container: "{{ cephs3_dp_storage_container }}"

default_org_id: "0133782666818437120"
frac_org_id: ""

bucket: "igotprod"
secor_bucket: "igotlogs"

dashboards_frac_backend_host: "frac-dictionary.igotkarmayogi.gov.in"
dashboards_broker_compression: "none"


platform_rating_survey_id: "1697521678752"

spark:
  home: "{{ analytics.home }}/spark-{{ spark_version }}-bin-hadoop2.7"
  public_dns: 54.255.154.146
  master:
    url: spark://172.31.11.117:7077
    host: 172.31.11.117
  worker:
    instances: 1
    cores: 12
    memory: 36g
  driver:
    memory: 50g
    cores: 12
    memoryOverhead: 4g
  executor:
    instances: 1
    cores: 12
    memory: 28g
    memoryOverhead: 5g
  driver_memory: 22g
  executor_extraJavaOptions: -Dconfig.file=/mount/data/analytics/models-{{ model_version }}/{{ env }}.conf -Dlog4j.configurationFile=file:////mount/data/analytics/models-{{ model_version }}/log4j2.xml
  driver_extraJavaOptions: -Dconfig.file=/mount/data/analytics/models-{{ model_version }}/{{ env }}.conf -Dlog4j.configurationFile=file:////mount/data/analytics/models-{{ model_version }}/log4j2.xml
  memory_fraction: 0.3
  storage_fraction: 0.5
  executor_memory: 28g
  heap_conf_str: '"-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -Xms250m {{ heap_memory }} -XX:+UseStringDeduplication"'

comms_console_prarambh_cbp_ids_for_envs: "do_11359618144357580811,do_113569878939262976132,do_1136364937253437441916,do_113474579909279744117,do_113651330692145152128,do_1134122937914327041177,do_113473120005832704152,do_1136364244148060161889"
  
  
